version: '3.8'

services:
  db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './db-data:/var/lib/mysql'
  db_test:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports: 
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - './db-data-test:/var/lib/mysql'